#cloud-config
# vim: syntax=yaml
#
growpart: { mode: "off" }
locale: en_US.UTF-8
resize_rootfs: false
ssh_pwauth: false
system_info:
  default_user:
    name: {{ cookiecutter.ssh_username }}
packages:
  - ntp
users:
  - default
  - name:  {{ cookiecutter.ssh_username }}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, adm, docker, sudo
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - <USER_KEY>

# expand the root partition up to a certain location on the disk
# note that the value is the marker on the disk where the root partion will end
# and can be in MB, GB or % of overall disk (see parted units)
# note that the root partition is where container images are stored
#
# create an additional partition and mark where on the disk it starts and stops
# this can be used later for a cluster filesystem
runcmd:
  # Turn off the firewall.
  - [ufw, disable]
  # Get Docker.
  - curl -fsSL https://get.docker.com | sh
  # Get K3s
  - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ cookiecutter.k3s_version }}"" sh -s - server --cluster-init
  # Allow reading the k3s yaml
  - chmod +r /etc/rancher/k3s/k3s.yaml
