# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.238.0/containers/ubuntu/.devcontainer/base.Dockerfile

# [Choice] Ubuntu version (use ubuntu-22.04 or ubuntu-18.04 on local arm64/Apple Silicon): ubuntu-22.04, ubuntu-20.04, ubuntu-18.04
FROM ubuntu:jammy-20220531

# RUN apt update && export DEBIAN_FRONTEND=noninteractive \
#     && apt -y install --no-install-recommends python3 lxd
