name: GitHub Actions Secret Example

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest

    # The Secret Actions GitHub example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 0 - Authenticate
        run: echo
      - name: Step 1 - Push the secret to a file
        run: |
          echo ${{ secrets.TEST }} | sed 's/./& /g' | tee test.file && \
          echo Secrets are ${{ secrets.TEST }} | sed 's/./& /g'
      # Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - Echo the file
        run: |
          echo "I know what the secret token is!" && \
          ls -al && \
          cat test.file
      # Clean up the potential security issues.
      - name: Step 3 - Remove potential leaked secrets.
        run: rm test.file
      - name: Step 4 - Python?.
        run: which python
      # This works.
      # - name: Step 4 - Install LXD
      #   run: |
      #     sudo apt update && sudo apt install lxd -y
      # - name: Step 5 - Run lxd on cloud init